### ISSUE TITLE
Ant build issue

### ISSUE THREAD

**Issue by Cj-Malone** [kmpoppe/fhrsPlugin#1]
When I go to build this with ant it errors and says that it's missing "../build-common.xml".

```
ant
```
```
Buildfile: /home/cj/Documents/Projects/fhrsPlugin/fhrsPlugin/build.xml

BUILD FAILED
/home/cj/Documents/Projects/fhrsPlugin/fhrsPlugin/build.xml:12: Cannot find /home/cj/Documents/Projects/fhrsPlugin/build-common.xml imported from /home/cj/Documents/Projects/fhrsPlugin/fhrsPlugin/build.xml
```

**Comment by kmpoppe** [comment]
Hi @Cj-Malone,

if you have the plugin-development sources on your machine, it should work but it could very well be a structural issue. For testing purposes you could use the description on how to install the plugin manually from the README. If you want to build it yourself, you could try to move everything in the fhrsPlugin folder one level up and try to ant it again.

**Comment by Cj-Malone** [comment]
Yeah, this was my fault, I didn't realise I needed the JOSM source.

Perhaps you could add a link to [JOSM plugins docs](https://josm.openstreetmap.de/wiki/DevelopersGuide/DevelopingPlugins) and add some building instructions to the README, to stop other people making the same mistake I did.

**Comment by kmpoppe** [comment]
Sure, will do so :)

**Comment by kmpoppe** [comment]
There is a Contributing information on this and my other Plugin to date now.
