### ISSUE TITLE
Unexpected Error When Cancelling 'Input' Window

### ISSUE THREAD

**Issue by pqhf5kd** [kmpoppe/fhrsPlugin#12]
JOSM 16538, firsPlugin 0.1.5

If an object doesn't have an address, the 'Input' window will popup after clicking 'Search entry' asking for a town or address. If you cancel this 'Input' window JOSM reports an unexpected error and asks you to update plugins.

**Comment by kmpoppe** [comment]
Good morning, @pqhf5kd ... Why in the world do I only ever test one of the buttons 🤦 .
I'll get right to it, thanks for reporting!
