### ISSUE TITLE
Error thrown when FHRS Business's data not selected

### ISSUE THREAD

**Issue by TonyS999** [kmpoppe/fhrsPlugin#2]
Selected object.
FHRS - Search Entry
List of business's presented
select OKay with no business selected - throws Java exception (ArrayIndexOutOfBoundsException)

**Comment by kmpoppe** [comment]
Hi @TonyS999,

Hrm. I thought I had tried that before and hadn't gotten an error 🤷‍♂️. I shall need to revise that :-)

Could you do me a favour and copy the call stack that's presented to you either as text or as a screenshot and paste it here?

Thanks!

**Comment by TonyS999** [comment]
![FHRS Plugin 26_06_2020 13_09_37](https://user-images.githubusercontent.com/39731333/85857317-8368cf80-b7b1-11ea-9a41-d59e004bf482.png)

**Comment by TonyS999** [comment]
Sorry - closed by mistake. Cant see how to reopen or undo the close.

**Comment by kmpoppe** [comment]
As you see the Issue reopens once you comment again. I'll look into this.

**Comment by DaveF63** [comment]
1. If there's only one option could it be selected by default?

2. Unsure of the criteria it's using to search,, but on certain entities I'm receiving this error when an option is selected.

**Comment by kmpoppe** [comment]
1. Sure thing, that'll be the next step forward

2. Could you try to replicate that step by step and write it down so that I
can see what's wrong with the API answers?

K

DaveF63 <notifications@github.com> schrieb am Fr., 26. Juni 2020, 17:41:
