### ISSUE TITLE
Cancel confirmation should only trigger when an option has been amended

### ISSUE THREAD

**Issue by DaveF63** [kmpoppe/fhrsPlugin#3]
Hi
Cancel confirmation need only trigger when a tag box has been amended (Both Get & Search options)

**Comment by kmpoppe** [comment]
Hi @DaveF63,

I'm not quite sure what you mean? The "Setting values was cancelled." message currently appears when you Cancel selecting any search result and then you Cancel the merge Dialog (so that nothing was changed). Which one would you rather have say something else?

**Comment by DaveF63** [comment]
Select object in JOSM
Click on Get information
Displays the "select which options to merge.. " dialog.
Click Cancel 
If no amendments were made it still displays this message:
It only needs to be displayed if amendments are about to be lost.

![image](https://user-images.githubusercontent.com/9528328/85876815-29c2ce00-b7ce-11ea-8198-f594a607fb98.png)
