### ISSUE TITLE
Restrict search to the local authority the selected item is within.

### ISSUE THREAD

**Issue by DaveF63** [kmpoppe/fhrsPlugin#4]
Restrict search to the local authority which the selected item is within.

I'm getting options of similarly named establishments from across the country.

**Comment by kmpoppe** [comment]
This might be due to the fact that there's no address on the object. It
then tries to search by name.

To accomplish this I need to find a way to get the surrounding borough
which might be tricky but I'll try

K

DaveF63 <notifications@github.com> schrieb am Fr., 26. Juni 2020, 17:47:

**Comment by kmpoppe** [comment]
Short summary of what needs to be done for this:

1.  Get is_in for node/way from overpass:
```
[timeout:10][out:json];
node(2772000146);is_in;nwr(pivot);
out ids;
```
2. Remove relations we know are NOT FHRS-Authorities:
`58447,62149,6038068` (GB-ENG, GBR, Island) ...
3. Use OSM API `https://api.openstreetmap.org/api/0.6/relations?relations=...` to get all relations and pick boundary=administrative between level 5 and 9
4. Replace "London Borough of" and "Royal London Borough of" from the relation's name
5. Search remaining names in the list of authorities
6. Use Search in the FHRS `GET /Establishments?...`

**Comment by kmpoppe** [comment]
@DaveF63 This will now work in 0.2 - searching will now take a few moments longer (because it needs to list the fhrs-authority-ids of the surrounding area). Please try if this works for you.
