### ISSUE TITLE
0.1.3 Release Listed As 0.1.2 In Plugins List

### ISSUE THREAD

**Issue by pqhf5kd** [kmpoppe/fhrsPlugin#6]
I've tried downloading and reinstalling the latest release (0.1.3) multiple times but JOSM still reports version 0.1.2 in the plugin window.

I'm fairly sure I am using version 0.1.3 because I can see the issues fixed no longer affect me.

**Comment by kmpoppe** [comment]
Hi @pqhf5kd,
yep, you're totally right, I forgot to change the version number in the MANIFEST file 🤦 .
As this is a minor issue, I'll just close this one and remember to change the version number next time.
Thanks for reminding me!
