### ISSUE TITLE
Unable To Search By Name

### ISSUE THREAD

**Issue by pqhf5kd** [kmpoppe/fhrsPlugin#8]
> The menu "Search entry" looks up establishments in FHRS using this three options in order:
> 
> name and address
> address only
> **name only**

<img width="583" alt="image" src="https://user-images.githubusercontent.com/20027419/85916191-8534a080-b84e-11ea-9f55-b968685ecd1a.png">

Is searching by name disabled while you work on #4 ?

If #7 can be fixed and we're able to search by name, this plugin would even more useful allowing us to population address and FHRS info at once.

Thanks :)

**Comment by kmpoppe** [comment]
No, searching by name isn't disabled per se, there's just something wrong in my logic to allow searching without an address... Will need to figure out what went wrong. Which node/way did you select to reach this message?

**Comment by pqhf5kd** [comment]
Here are two examples:
- 6695231888
- 6691214599

**Comment by kmpoppe** [comment]
I changed the logic to be name & address OR address. Name only will not work consistently, so this is not an option for the time being ;-) ... And of course the plugin now asks for an address if there's none in the object.

**Comment by kmpoppe** [comment]
When using the Node 6691214599 and entering "station road new milton" when prompted, you get this result to merge:
![image](https://user-images.githubusercontent.com/24451207/85929398-b34ccb80-b8b4-11ea-9f8d-49d2a892fe63.png)
I guess this now works as intended :-D
Will publish 0.1.5 in a few minutes for you.
BTW: I can't find Dukes Station Cafe, I guess it has a new name now?

**Comment by pqhf5kd** [comment]
This works great but is it possible to cache the last entry in the 'Input' window? That way a user can go along a street or through a whole town without having to type, or paste, the input.

**Comment by pqhf5kd** [comment]
@kmpoppe I thought that commenting would reopen this but I guess not?

**Comment by kmpoppe** [comment]
@pqhf5kd I had thought so as well, but I guess one needs to click "Reopen and comment" (If only I can do that, that might be the reason)...
Your wish is certainly understandable and possible, but could you please open another issue with that so that I can reference that in the commit message (that way one can keep track of the changes in more detail)?
Thanks!
